### ISSUE TITLE
3 Syntax Error for Program SAPLZAMP_CONFIG_MP

### ISSUE THREAD

**Issue by nomssi** [abap-observability-tools/abap-metrics-provider#181]
While trying to install via abapGit:
![image](https://user-images.githubusercontent.com/18452507/109628280-da922180-7b42-11eb-9f5a-de9a85dde425.png)

**Comment by nomssi** [comment]
After forcing activation:
Table ZAMPV_CONFIG_SCE not active in ABAP Dictionary 
Import of object ZAMP_CONFIG_MP failed 
Import of object ZAMPV_CONFIG_PROV failed 
Import of object ZAMPV_CONFIG_SCEV failed

**Comment by JohannesKonings** [comment]
On which system version did the error occur?
I could reinstall the abap-metrics-provider on my local dev trial NW7.52 with the latest status of the repository.

**Comment by JohannesKonings** [comment]
Thanks for reporting, we'll have a look

**Comment by JohannesKonings** [comment]
@nomssi could you try again? We regenerated the views from the A4H system.
If it not working, please open again this issue. Thanks.

**Comment by Goala** [comment]
@nomssi I just tried to import it to my A5H System. 
You may need to pull twice. 
After the first activation error pull again and the activation should work.

**Comment by nomssi** [comment]
I can confirm the current version could be activated without issues.
Thanks and best regards

**Comment by treee111** [comment]
Hi @Goala  and @JohannesKonings,
I had the same issues today while importing this Repo using abapGit v1.100.0.
Using abapGit v1.106.0 and v1.111.0 it worked.

I know that behaviour from other repos, it depends which version of abapGit was used to serialize the push and which to pull.
For your information if case someone has a similar issue.
