### ISSUE TITLE
SM50/SM51 metrics

### ISSUE THREAD

**Issue by Goala** [abap-observability-tools/abap-metrics-provider#31]

**Comment by JohannesKonings** [comment]
@Goala I put that together with SM50. SM51 is implicitly integrated.

**Comment by JohannesKonings** [comment]
docu and example dashboard is still missing

**Comment by JohannesKonings** [comment]
dashboard added with this PR: https://github.com/abap-observability-tools/abap-metrics-provider/pull/129

**Comment by JohannesKonings** [comment]
accidentally done with https://github.com/abap-observability-tools/abap-metrics-provider/commit/bb4b4a2c01046b3cd017f723f112dfb11781f51d
