### ISSUE TITLE
Concept for deleting metrics from zamp_store

### ISSUE THREAD

**Issue by Goala** [abap-observability-tools/abap-metrics-provider#51]

**Comment by JohannesKonings** [comment]
@Goala  Deleting in which use cases?

**Comment by Goala** [comment]
because of that discussion (https://github.com/Goala/abap-metrics-provider/pull/49#discussion_r553813988)
only as an reminder. if there isn't a use case we can also delete later

**Comment by JohannesKonings** [comment]
could that be a concept?
https://github.com/abap-observability-tools/abap-metrics-provider/issues/103
