### ISSUE TITLE
Broken Json for scenrios not already run

### ISSUE THREAD

**Issue by Goala** [abap-observability-tools/abap-metrics-provider#70]
Json output is broken when selected scenrio has noch metrics inside metrics store 
![grafik](https://user-images.githubusercontent.com/15353332/104285125-6ed0f800-54b3-11eb-8e59-528443bf5248.png)

**Comment by JohannesKonings** [comment]
this converter has to be changed: https://gitlab.haufedev.systems/devinfra/maas/instance-config/saptest/-/pipelines/189807
