### ISSUE TITLE
Set content type for responses

### ISSUE THREAD

**Issue by Goala** [abap-observability-tools/abap-metrics-provider#71]

**Comment by JohannesKonings** [comment]
Maybe the easiest way is to add an exporting parameter to this interface: https://github.com/Goala/abap-metrics-provider/blob/main/src/zamp_converter/zif_amp_converter.intf.abap
 And use the content type here: https://github.com/Goala/abap-metrics-provider/blob/main/src/zamp_scraper/zcl_amp_scraper.clas.abap
