### ISSUE TITLE
change zcl_amp_metrics_ to zcl_amp_conv_ in plantuml

### ISSUE THREAD

**Issue by JohannesKonings** [abap-observability-tools/abap-metrics-provider#90]
https://github.com/abap-observability-tools/abap-metrics-provider/blob/5c6618d1346447cc1c6516271649c3effcb6ea03/architecture/architecture_class.plantuml#L41

**Comment by larshp** [comment]
also checkou out https://abaplint.app/stats/abap-observability-tools/abap-metrics-provider/uml its updated daily
